### ISSUE TITLE
Compiling unit tests with cFS bootes-rc2

### ISSUE THREAD

**Issue by the1jacobmiller** [nasa/HS#2]
The provided unit tests do not compile with the bootes-rc2 release of cFS. 

The unit test README states that "The ut-assert framework, stubs, and hooks are located in the directory cfe/tools/ut-assert". This is no longer the case. I found an older version of cfe that had this ut-assert folder and managed to get the unit tests to compile with that, but many of the unit tests failed, likely because the functions in ut-assert are out of date.

It seems that many of the functions within the old ut-assert folder used by these unit tests have moved to various places in cfe, osal, and psp and have since been updated. I am attempting to move files around and link libraries to compile with the updated cFS, but have not had any luck so far.

Below are the versions of cfe, osal, and psp I am using:
- cfe v6.7.0+dev298
- osal v5.0.0+dev250
- psp v1.4.0+dev76

**Comment by skliper** [comment]
Updated for Caelum in f72c7b106064d1f4f9de6d72fc602e67667dcc05 and Draco in 2a34024eee6146a26f5d3762878b966aad90315f.
