### ISSUE TITLE
HS idle task only executes once and exits... reports CPU hogging all the time

### ISSUE THREAD

**Issue by skliper** [nasa/HS#21]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/HS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
HS idle task used to have a while loop (from 2.3.2 tag):
https://github.com/nasa/HS/blob/192a10f1adfb1a2cd5c64bd6c5be918058e9441c/fsw/src/hs_custom.c#L60-L84

Now just runs once:
https://github.com/nasa/HS/blob/c5ef5acf65ca346270f721e22620e9321a930075/fsw/src/hs_custom.c#L51-L80

**To Reproduce**
Running cFS with HS reports hogging every time...
```
EVS Port1 66/1/HS 61: CPU Hogging Detected
1980-012-14:03:25.80827 HS App: CPU Hogging Detected
```

**Expected behavior**
Task should run in a loop and realistic margin should be getting reported

**System observed on:**
 - OS: Linux
 - Versions: 2.4.1+

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Do we just want to add the while loop back in?

**Comment by astrogeco** [comment]
[CCB:2022-05-25](https://github.com/nasa/cFS/wiki/CCB:-2022.05.25) New PR introduced
