### ISSUE TITLE
Performance ID usage is inconsistent in HS app

### ISSUE THREAD

**Issue by skliper** [nasa/HS#7]
Anytime a task goes into a system delay (for example a pend on message receipt or task delay), an app should do the following:

CFE_ES_PerfLogExit(<performance_id>);
<do the delay function>
CFE_ES_PerfLogEntry(<performance_id>);

There appear to be some cases in HS where a task delay called, but the performance monitor is not exited.
Other apps should also be checked for consistent usage.

Imported from GSFCCFS-1208

**Comment by paulober** [comment]
Should there be a check for `HS_POST_PROCESSING_DELAY != 0` in/befor [hs_monitors.c#L130](https://github.com/nasa/HS/blob/0ddd1db3cfc37ccab2e7541d661f10cce9c19ea2/fsw/src/hs_monitors.c#L130) and [hs_monitors.c#L271](https://github.com/nasa/HS/blob/0ddd1db3cfc37ccab2e7541d661f10cce9c19ea2/fsw/src/hs_monitors.c#L271)? 

(As in [hs_app.c#130](https://github.com/nasa/HS/blob/0ddd1db3cfc37ccab2e7541d661f10cce9c19ea2/fsw/src/hs_app.c#L130))

**Comment by skliper** [comment]
Actually it'd probably be better for all three cases to set an element within the global structure to the config define at initialization, then just check for that global value to be nonzero before actually used.  We are trying to reduce the reliance on compile time conditionals.
