### ISSUE TITLE
HS does not calculate CPU utilization correctly on multi-core systems

### ISSUE THREAD

**Issue by dmknutsen** [nasa/HS#85]
**Checklist (Please check before submitting)**

* [x ] I reviewed the [Contributing Guide](https://github.com/nasa/HS/blob/main/CONTRIBUTING.md).
* [x ] I reviewed the [README file](https://github.com/nasa/HS/blob/main/README.md) to see if the feature is in the major future work.
* [x ] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
HS does not calculate CPU utilization correctly on multi-core systems.  

**Describe the solution you'd like**
HS has only one idle task.  Multiple idle tasks would need to be spawned/pinned to each core in an SMP/multi-core setup in order to correctly calculate CPU utilization.  Alternatively, OS specific task hooks could be utilized to report the CPU utilization for each core...which would likely be the most accurate/desired approach.   

**Requester Info**
Dan Knutsen
NASA GSFC

**Comment by skliper** [comment]
See also:
- #3 
- #4

**Comment by jphickey** [comment]
I checked into the various CPU use APIs, but there doesn't seem to be much standardization here across platforms.  POSIX does have some limited facilities (e.g. the `times()` call) but that's really just for the CPU time of the calling process and not for the system as a whole.   One can get more detailed information using platform-specific methods, such as querying the `/proc` filesystem on Linux. 

My current thinking is that the abstraction belongs in the PSP in the form of PSP modules - a single "Linux" module could cover all Linux-based boards.  The current "idle loop" fallback could be another PSP module where there are no better options (though I'd never recommend using this, except perhaps on the simplest of processors that have no power-management logic, as it will keep the processor "on" all the time and can increase power usage drastically).
